# Generated by Django 3.0.5 on 2021-04-29 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorDataModel',
            fields=[
                ('AdvisorId', models.AutoField(primary_key=True, serialize=False)),
                ('AdvisorName', models.CharField(max_length=50)),
                ('AdvisorPhotoURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorBookingModel',
            fields=[
                ('BookingId', models.AutoField(primary_key=True, serialize=False)),
                ('BookingTime', models.DateTimeField()),
                ('AdvisorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beadvisor.AdvisorDataModel')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beuser.UserModel')),
            ],
        ),
    ]
